"""full_pipeline_notemporal.py
=============================
pRF pipeline without temporal models.

Skipped stages (vs full_pipeline_with_adaptrans):
  - Duration Gaussian filter  (no pref_dur / sigma_dur)
  - AdapTrans ON/OFF filter    (no onset/offset decomposition)

Retained stages:
  1. Load cochlea PSTH results
  2. Power-law sharpening (alpha)
  3. Chunk into tone-ON windows -> mean rate per tone
  4. Build boxcar train (amplitude = mean rate)
  5. Assemble N runs from run design
  6. HRF convolution -> BOLD

Each run is assembled from the same per-sequence boxcar trains, placed at
onset times generated by generate_run_design() with a per-run seed.
"""

import logging
from multiprocessing import Pool
from pathlib import Path

import numpy as np

from auditory_prf.prf_pipeline.load_extract_cf_timecourse import load_population_psth
from auditory_prf.prf_pipeline.powerlaw_function import apply_powerlaw_population
from auditory_prf.prf_pipeline.chunk_timecourse import chunk_from_id
from auditory_prf.prf_pipeline.adaptrans_onoff_filters import build_prf_boxcar_train
from auditory_prf.prf_pipeline.hrf import build_hrf_kernel, convolve_hrf, SUBCORTICAL_PARAMS
from auditory_prf.prf_pipeline.run_assembly import make_seq_id_fn, generate_run_design, assemble_run_bold
from auditory_prf.utils.result_saver import ResultSaver
from auditory_prf.utils.logging_configurator import LoggingConfigurator
from auditory_prf.utils.condition_map import SILENCE_SEQ_ID

logger = logging.getLogger(__name__)

# ── multiprocessing worker (module-level so it is picklable) ─────────────────
_worker: dict = {}


def _worker_init(per_seq, hrf_kernel, total_run_dur_s, cf_hz, tr_s, signal_dt_s):
    _worker["per_seq"]         = per_seq
    _worker["hrf_kernel"]      = hrf_kernel
    _worker["total_run_dur_s"] = total_run_dur_s
    _worker["cf_hz"]           = cf_hz
    _worker["tr_s"]            = tr_s
    _worker["signal_dt_s"]     = signal_dt_s


def _assemble_one(task: tuple) -> tuple:
    run_idx, run_design = task
    result = assemble_run_bold(
        per_seq          = _worker["per_seq"],
        run_design       = run_design,
        total_run_dur_s  = _worker["total_run_dur_s"],
        hrf_kernel       = _worker["hrf_kernel"],
        cf_hz            = _worker["cf_hz"],
        tr_s             = _worker["tr_s"],
        signal_dt_s      = _worker["signal_dt_s"],
        apply_adaptrans_flag=False,
    )
    return run_idx, run_design, result["bold_combined"], result["bold_on"], result["t_tr"]


# ── experiment defaults ──────────────────────────────────────────────────────
EXP_NAME        = "dipc_test_250225_01"
DEFAULT_BASE_DIR = Path(f"./models_output/{EXP_NAME}")

# ── run design defaults ──────────────────────────────────────────────────────
TONE_ON_MS      = (35, 45, 60, 75, 100, 150, 251, 488)
ISI_MS          = (100,) * len(TONE_ON_MS)
FREQ_RANGE      = (450, 1600, 3)    # (min_hz, max_hz, num_cfs) Greenwood-spaced
NULL_FRACTION   = 0.25
TRIAL_DURATION_S = 20.0
OPENING_BLANK_S  = 10.0
CLOSING_BLANK_S  = 10.0
ITI_RANGE_S      = 0
N_RUNS           = 4
BASE_SEED        = 42               # run k uses seed BASE_SEED + k


def run_pipeline(
        exp_name: str = EXP_NAME,
        results_dir: Path = None,
        alpha: float = 2.0,
        cf=10,
        output_dir: Path = None,
        # run design
        tone_on_ms: tuple = TONE_ON_MS,
        isi_ms: tuple = ISI_MS,
        freq_range: tuple = FREQ_RANGE,
        null_fraction: float = NULL_FRACTION,
        trial_duration_s: float = TRIAL_DURATION_S,
        opening_blank_s: float = OPENING_BLANK_S,
        closing_blank_s: float = CLOSING_BLANK_S,
        iti_range_s: tuple = ITI_RANGE_S,
        n_runs: int = N_RUNS,
        base_seed: int = BASE_SEED,
        run_designs: list = None,   # pre-built list of run_designs; overrides n_runs
        total_run_dur_s: float = 720.0,
        # HRF
        hrf_params: dict = None,
        tr_s: float = 1.6,
        # parallelism
        n_workers: int = 1,
):
    _output_dir = output_dir or Path(f"./output/{exp_name}_notemporal")
    LoggingConfigurator(
        output_dir=_output_dir,
        log_filename="pipeline_notemporal.log",
        file_level=logging.DEBUG,
        console_level=logging.INFO,
    ).setup()

    _results_dir = (results_dir if results_dir is not None else DEFAULT_BASE_DIR)
    _results_dir = Path(_results_dir).expanduser().resolve()
    logger.info("Experiment       : %s", exp_name)
    logger.info("Results dir      : %s", _results_dir)

    npz_files = sorted(_results_dir.rglob("*.npz"))
    if not npz_files:
        logger.error("No .npz files found in %s", _results_dir)
        return {}
    logger.info("Found %d NPZ file(s)", len(npz_files))

    # ── HRF kernel (built once) ──────────────────────────────────────────────
    signal_dt_s = 1e-3
    _hrf_params = hrf_params if hrf_params is not None else SUBCORTICAL_PARAMS
    hrf_kernel, _ = build_hrf_kernel(**_hrf_params, dt=signal_dt_s, duration=32.0)
    logger.info("HRF kernel: %d samples | TR=%.3f s", len(hrf_kernel), tr_s)

    # ── build run design params (no PsychoPy needed) ─────────────────────────
    from auditory_prf.utils.stimulus_utils import calc_cfs
    desired_freqs = calc_cfs(freq_range, species='human')
    stimuli       = [(ton, isi, freq)
                     for ton, isi in zip(tone_on_ms, isi_ms)
                     for freq in desired_freqs]
    n_null        = int(np.floor(len(stimuli) * null_fraction / (1 - null_fraction)))
    base_trials   = stimuli + [(0, 0, None)] * n_null

    seq_id_fn  = make_seq_id_fn(freq_range,
                                tone_on_ms_options=tuple(tone_on_ms),
                                isi_ms_options=tuple(isi_ms))
    logger.info("Base trials: %d active + %d null = %d total",
                len(stimuli), n_null, len(base_trials))

    # ── Phase 1: per-sequence processing ─────────────────────────────────────
    # Build boxcar trains for every sequence found in results_dir.
    per_seq: dict = {}

    for i, npz_path in enumerate(npz_files, 1):
        logger.info("[%d/%d] %s", i, len(npz_files), npz_path.name)

        population_psth, time_axis, cf_index, cf_hz, seq_id = load_population_psth(
            npz_path, cf
        )
        dt_s         = time_axis[1] - time_axis[0]
        total_dur_ms = (time_axis[-1] + dt_s) * 1000.0

        # power-law sharpening across all CFs, extract target CF
        sharpened = apply_powerlaw_population(population_psth, alpha)[cf_index, :]

        if seq_id == SILENCE_SEQ_ID:
            # silence: flat train at the spontaneous rate (mean over full duration)
            spont_rate = float(np.mean(sharpened))
            n_samples  = int(round(total_dur_ms))
            train      = np.full(n_samples, spont_rate)
            logger.debug("  seq_id=%s | CF=%.0f Hz | spont_rate=%.2f sp/s | train len=%d",
                         seq_id, cf_hz, spont_rate, len(train))
        else:
            # chunk into tone-ON windows
            result, tone_dur_ms, isi_ms_val = chunk_from_id(sharpened, time_axis, seq_id)
            mean_rates_on = [np.mean(c) for c in result["chunks"]]

            # boxcar train: amplitude = raw mean rate (no duration Gaussian)
            train = build_prf_boxcar_train(
                mean_rates_on,
                result["onsets_ms"],
                result["offsets_ms"],
                total_dur_ms,
                dt_ms=1.0,
            )
            logger.debug("  seq_id=%s | CF=%.0f Hz | %d tones | train len=%d",
                         seq_id, cf_hz, len(mean_rates_on), len(train))

        per_seq[seq_id] = {
            "train":    train,
            "cf_hz":    cf_hz,
            "cf_index": cf_index,
        }

    logger.info("Phase 1 complete — %d sequences processed.", len(per_seq))

    # ── Validate seq_id alignment ─────────────────────────────────────────────
    expected_seq_ids = {seq_id_fn(ton, isi, freq)
                        for ton, isi, freq in stimuli} | {SILENCE_SEQ_ID}
    missing = expected_seq_ids - set(per_seq.keys())
    if missing:
        sample = sorted(missing)[:3]
        raise ValueError(
            f"Stimulus params do not match .npz files in results_dir.\n"
            f"{len(missing)} expected seq_ids not found in per_seq "
            f"(e.g. {sample}).\n"
            f"Check that FREQ_RANGE, ALL_DURATIONS, and ISI_MS match "
            f"the WAV files used to generate the cochlear results."
        )

    # ── Phase 2: per-run assembly ─────────────────────────────────────────────
    cf_hz_used = next(iter(per_seq.values()))["cf_hz"]
    all_runs: dict = {}

    _designs = run_designs if run_designs is not None else [
        generate_run_design(
            base_trials, seq_id_fn,
            trial_duration_s=trial_duration_s,
            opening_blank_s=opening_blank_s,
            iti_range_s=iti_range_s,
            seed=base_seed + i,
        )
        for i in range(n_runs)
    ]
    logger.info("Phase 2: assembling %d run(s) with %d worker(s).",
                len(_designs), n_workers)

    tasks = list(enumerate(_designs))

    if n_workers > 1:
        with Pool(
            processes=n_workers,
            initializer=_worker_init,
            initargs=(per_seq, hrf_kernel, total_run_dur_s,
                      cf_hz_used, tr_s, signal_dt_s),
        ) as pool:
            results = pool.map(_assemble_one, tasks)
    else:
        results = [_assemble_one(t) for t in tasks]

    for run_idx, run_design, bold_combined, bold_on, t_tr in results:
        all_runs[f"run_{run_idx + 1:02d}"] = {
            "run_design":    run_design,
            "bold_combined": bold_combined,
            "bold_on":       bold_on,
            "t_tr":          t_tr,
            "seed":          base_seed + run_idx if run_designs is None else None,
        }
    logger.info("  BOLD shape: %s", bold_combined.shape)

    # ── Save ─────────────────────────────────────────────────────────────────
    saver = ResultSaver(_output_dir)
    saver.save_npz(
        {
            "exp_name": exp_name,
            "cf":       cf,
            "alpha":    alpha,
            "tr_s":     tr_s,
            **{k: v["bold_combined"] for k, v in all_runs.items()},
        },
        f"{exp_name}_notemporal_cf{cf:03d}_bold.npz",
    )
    logger.info("Saved BOLD to %s", _output_dir)

    return all_runs


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--cf", type=int, default=0,
                        help="CF index (0-based). Pass $SLURM_ARRAY_TASK_ID.")
    parser.add_argument("--results-dir", type=str, default=None,
                        help="Path to cochlea NPZ results directory.")
    parser.add_argument("--output-dir", type=str, default=None)
    parser.add_argument("--alpha", type=float, default=2.0)
    args = parser.parse_args()

    run_pipeline(
        cf=args.cf,
        results_dir=Path(args.results_dir) if args.results_dir else None,
        output_dir=Path(args.output_dir)   if args.output_dir   else None,
        alpha=args.alpha,
    )
